FROM node:22-alpine
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

WORKDIR /app
COPY package*.json ./
RUN npm install -g pnpm \
  && pnpm install
COPY . .
RUN pnpm build
EXPOSE 3001
CMD ["pnpm", "start","-p", "3001"]